name: Remote Proto Generation

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Protos
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      
      - name: Install Protoc & Plugins
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Code
        run: |
          mkdir -p out
          # Добавляем путь к бинарникам Go, чтобы protoc увидел плагины
          PATH=$PATH:$(go env GOPATH)/bin protoc \
            --go_out=out \
            --go-grpc_out=out \
            payment/payment.proto

      - name: Push to Generated Repo
        env:
          GH_TOKEN: ${{ secrets.PROTO_GEN_TOKEN }}
        run: |
          # Путь должен соответствовать go_package из твоего .proto файла
          GEN_PATH="out/github.com/Almukhammed77/order-payment-generated"
          
          if [ ! -d "$GEN_PATH" ]; then
            echo "Ошибка: Директория $GEN_PATH не найдена!"
            exit 1
          fi

          cd $GEN_PATH
          git init
          # Принудительно создаем ветку main, чтобы избежать ошибки refspec
          git checkout -b main
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-update gRPC code"
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/Almukhammed77/order-payment-generated.git
          # Отправляем изменения в репозиторий B
          git push -f origin main
